# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    update_code_signing_settings(
           use_automatic_signing: false,
           path: "demo-application.xcodeproj",
           team_id: "D2739LNA3V",
           bundle_identifier: "com.anko.demo-app.dev",
           profile_name: "DemoApplication"
    )
    build_app(
      export_method:"development"
    )
  end
lane :alpha do
    update_code_signing_settings(
           use_automatic_signing:false,
           path: "demo-application.xcodeproj",
           team_id: "D2739LNA3V",
           bundle_identifier: "com.anko.demo-app.qa",
           profile_name: "DemoApplication"
    )
    build_app(
      export_method:"development"
    )
  end

  lane :custom_lane do
    build_app(
  export_method: "development",
    )

   appcenter_upload(
            api_token: "d91388a16798c4ba5a5b619079f2ba1dca279adc",
            owner_name: "avovchuk-f8sy",
            owner_type: "user", # Default is user - set to organization for :app::c::enter: organiz
            app_name: "demo-application",
            file: "demo-application.ipa",
            notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )          
    # add actions here: https://docs.fastlane.tools/actions
  end
end
